package com.kw.knowone.encounter.service;

import static com.kw.knowone.encounter.entity.EncounterModels.*;
import java.io.IOException;import java.sql.Timestamp;import java.time.Clock;import java.time.Duration;import java.time.Instant;import java.time.LocalDate;import java.util.ArrayList;import java.util.List;import java.util.Map;import java.util.Set;import java.util.UUID;
import org.springframework.beans.factory.annotation.Value;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.web.multipart.MultipartFile;
import com.kw.knowone.common.crypto.FingerprintService;import com.kw.knowone.common.idempotency.IdempotencyService;import com.kw.knowone.common.idempotency.IdempotentResult;import com.kw.knowone.common.idempotency.MutationResponse;import com.kw.knowone.common.preview.PreviewTokenService;import com.kw.knowone.common.web.ApiException;import com.kw.knowone.common.web.CursorService;import com.kw.knowone.common.web.DataResponse;import com.kw.knowone.encounter.dto.EncounterDtos;import com.kw.knowone.encounter.repository.EncounterRepository;import com.kw.knowone.group.dto.GroupDtos.UserRef;import com.kw.knowone.group.entity.GroupMember;import com.kw.knowone.group.repository.GroupRepository;import com.kw.knowone.storage.FileValidationService;import com.kw.knowone.storage.StoragePort;import com.kw.knowone.storage.ValidatedUpload;import tools.jackson.databind.ObjectMapper;
import com.kw.knowone.task.service.TaskService;

@Service
public class EncounterService {
    private final EncounterRepository repository;private final GroupRepository groups;private final IdempotencyService idempotency;private final FileValidationService validator;private final StoragePort storage;private final PreviewTokenService previews;private final FingerprintService fingerprints;private final CursorService cursors;private final ObjectMapper json;private final Clock clock;private final Duration audioRetention;private final int maxImages;private final boolean processingEnabled;private final TaskService tasks;
    public EncounterService(EncounterRepository repository,GroupRepository groups,IdempotencyService idempotency,FileValidationService validator,StoragePort storage,PreviewTokenService previews,FingerprintService fingerprints,CursorService cursors,ObjectMapper json,Clock clock,TaskService tasks,@Value("${app.encounter.audio-retention:PT24H}")Duration audioRetention,@Value("${app.encounter.document-max-images:10}")int maxImages,@Value("${app.encounter.worker-enabled:false}")boolean processingEnabled){this.repository=repository;this.groups=groups;this.idempotency=idempotency;this.validator=validator;this.storage=storage;this.previews=previews;this.fingerprints=fingerprints;this.cursors=cursors;this.json=json;this.clock=clock;this.tasks=tasks;this.audioRetention=audioRetention;this.maxImages=maxImages;this.processingEnabled=processingEnabled;}

    public IdempotentResult create(UUID groupId,UUID userId,EncounterDtos.CreateRequest request,String key){validateType(request.recordType());return idempotency.executeGuarded(userId,"E01:"+groupId,key,request,()->requireGroup(groupId,userId),()->{UUID id=UUID.randomUUID();Encounter e=repository.insert(id,groupId,userId,request.recordType(),request.title(),request.occurredOn(),request.hospitalName());return response(201,toEncounter(e));});}
    public EncounterDtos.Page<EncounterDtos.Encounter> list(UUID groupId,UUID userId,LocalDate from,LocalDate to,String type,Integer requestedLimit,String cursor){requireGroup(groupId,userId);if(from!=null&&to!=null&&!from.isBefore(to))throw validation("날짜 범위가 올바르지 않습니다.");if(type!=null)validateType(type);int limit=limit(requestedLimit);EncounterCursor c=decodeEncounterCursor(cursor);List<Encounter> rows=repository.list(groupId,from,to,type,c==null?null:c.occurredOn(),c==null?null:c.createdAt(),c==null?null:c.id(),limit+1);boolean more=rows.size()>limit;List<Encounter> page=more?rows.subList(0,limit):rows;String next=more?encodeEncounterCursor(page.getLast()):null;return new EncounterDtos.Page<>(page.stream().map(this::toEncounter).toList(),next,more);}
    public EncounterDtos.Detail detail(UUID id,UUID userId){Encounter e=requireActive(id,userId);List<Source> sources=repository.sources(id);List<Job> jobs=repository.jobs(id,e.inputVersion());Revision revision=repository.currentRevision(id).orElse(null);var linked=tasks.linkedToEncounter(id,userId,20);List<Object> review=repository.currentReviewItems(id).stream().map(this::reviewDto).toList();var dto=toEncounter(e);return new EncounterDtos.Detail(dto.id(),dto.groupId(),dto.recordType(),dto.title(),dto.occurredOn(),dto.hospitalName(),dto.createdBy(),dto.inputVersion(),dto.version(),dto.createdAt(),dto.processingState(),dto.hasReviewItems(),dto.isSummaryStale(),revision==null?null:summary(revision),sources.stream().map(this::sourceDto).toList(),jobs.stream().map(this::jobDto).toList(),review,new java.util.ArrayList<>(linked.items()),linked.hasMore());}
    public IdempotentResult update(UUID id,UUID userId,EncounterDtos.UpdateRequest request,String key){return idempotency.executeGuarded(userId,"E04:"+id,key,request,()->requireActive(id,userId),()->{Encounter before=requireActive(id,userId);if(before.version()!=request.expectedVersion())throw version(before.version());if(request.title()==null&&request.occurredOn()==null&&request.hospitalName()==null)throw validation("수정할 메타 정보가 필요합니다.");String title=request.title()==null?before.title():textNode(request.title(),false,"title");LocalDate occurred=request.occurredOn()==null?before.occurredOn():dateNode(request.occurredOn(),"occurredOn");String hospital=request.hospitalName()==null?before.hospitalName():textNode(request.hospitalName(),true,"hospitalName");if(!repository.updateMeta(id,before.version(),title,occurred,hospital))throw version(before.version());return response(200,toEncounter(repository.findActive(id).orElseThrow()));});}

    public IdempotentResult uploadDocuments(UUID id,UUID userId,EncounterDtos.UploadMetadata metadata,List<MultipartFile> files,String key){if(files==null||files.isEmpty())throw validation("하나 이상의 문서가 필요합니다.");if(metadata.documents()==null)throw validation("documents가 필요합니다.");List<String> types=metadata.documents().isEmpty()?java.util.Collections.nCopies(files.size(),"LEGACY_UNCLASSIFIED"):metadata.documents().stream().map(EncounterDtos.DocumentMetadata::documentType).toList();if(types.size()!=files.size()||types.stream().anyMatch(v->!Set.of("PRESCRIPTION","DIAGNOSIS","MEDICINE_BAG").contains(v)))throw validation("파일별 documentType을 확인해 주세요.");List<ValidatedUpload> values=new ArrayList<>();try{for(MultipartFile file:files)values.add(validator.document(file));return registerUploads(id,userId,metadata,values,false,types,key);}catch(RuntimeException failure){values.forEach(v->storage.discard(v.staged()));throw failure;}}
    public IdempotentResult uploadAudio(UUID id,UUID userId,EncounterDtos.UploadMetadata metadata,MultipartFile file,String key){ValidatedUpload value=validator.audio(file);try{return registerUploads(id,userId,metadata,List.of(value),true,List.of(),key);}catch(RuntimeException failure){storage.discard(value.staged());throw failure;}}
    private IdempotentResult registerUploads(UUID id,UUID userId,EncounterDtos.UploadMetadata metadata,List<ValidatedUpload> values,boolean audio,List<String> documentTypes,String key){List<Promoted> promoted=new ArrayList<>();try{for(ValidatedUpload value:values)promoted.add(new Promoted(value,storage.promote(value.staged())));}catch(IOException failure){promoted.forEach(this::deleteQuietly);throw new ApiException(HttpStatus.SERVICE_UNAVAILABLE,"TEMPORARILY_UNAVAILABLE","파일 저장소를 사용할 수 없습니다.");}
        var request=Map.of("metadata",metadata,"files",values.stream().map(v->java.util.Base64.getEncoder().encodeToString(v.sha256())).toList());
        try{IdempotentResult result=idempotency.executeGuarded(userId,(audio?"E06:":"E05:")+id,key,request,()->requireActive(id,userId),()->doRegister(id,userId,metadata,promoted,audio,documentTypes));if(result.replayed())promoted.forEach(this::deleteQuietly);return result;}catch(RuntimeException failure){promoted.forEach(this::deleteQuietly);throw failure;}}
    private MutationResponse doRegister(UUID id,UUID userId,EncounterDtos.UploadMetadata metadata,List<Promoted> values,boolean audio,List<String> documentTypes){Encounter e=repository.lockActive(id);authorize(e,userId);checkVersions(e,metadata.expectedVersion(),metadata.expectedInputVersion());int added=(int)values.stream().filter(v->v.upload().image()).count();if(!audio&&repository.activeImageCount(id)+added>maxImages)throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"IMAGE_COUNT_LIMIT_EXCEEDED","기록의 이미지 문서 수 제한을 초과했습니다.");if(!repository.bumpInput(id,e.version(),e.inputVersion()))throw version(e.version());int next=e.inputVersion()+1;List<Source> sources=new ArrayList<>();for(int i=0;i<values.size();i++){Promoted value=values.get(i);Instant expires=audio?clock.instant().plus(audioRetention):null;UUID asset=repository.insertAsset(e.groupId(),userId,audio?"AUDIO":"DOCUMENT",value.key(),value.upload().originalName(),value.upload().mediaType(),value.upload().byteSize(),value.upload().sha256(),expires);UUID source=repository.insertSource(e.groupId(),id,asset,audio?"AUDIO":"DOCUMENT",audio?null:documentTypes.get(i));sources.add(repository.source(source).orElseThrow());}repository.obsoleteJobs(id,next);List<Job> queued=queuePendingSources(e.groupId(),id,next);List<Job> jobs=sources.stream().map(s->queued.stream().filter(j->s.id().equals(j.sourceId())).findFirst().orElseThrow()).toList();Encounter after=repository.findActive(id).orElseThrow();Object body=audio?new EncounterDtos.AudioUploadResponse(id,next,after.version(),sourceDto(sources.getFirst()),jobDto(jobs.getFirst())):new EncounterDtos.UploadResponse(id,next,after.version(),sources.stream().map(this::sourceDto).toList(),jobs.stream().map(this::jobDto).toList(),repository.activeImageCount(id));return response(202,body);}

    public EncounterDtos.Text text(UUID sourceId,UUID userId){Source s=requireActiveSource(sourceId,userId);return new EncounterDtos.Text(s.id(),s.sourceType(),s.status(),s.textVersion(),s.extractedText());}
    public IdempotentResult updateText(UUID sourceId,UUID userId,EncounterDtos.TextUpdate request,String key){return idempotency.executeGuarded(userId,"E08:"+sourceId,key,request,()->requireActiveSource(sourceId,userId),()->{Source s=requireActiveSource(sourceId,userId);Encounter e=repository.lockActive(s.encounterId());if(e==null)throw notFound();authorize(e,userId);if(!"AUDIO".equals(s.sourceType())||!"READY".equals(s.status()))throw invalidState("READY 음성 전사만 수정할 수 있습니다.");if(e.inputVersion()!=request.expectedInputVersion()||s.textVersion()!=request.expectedTextVersion())throw version(e.version());if(!repository.updateAudioText(sourceId,s.textVersion(),request.text().trim()))throw invalidState("전사 원문 상태가 변경되었습니다.");if(!repository.bumpInput(e.id(),e.version(),e.inputVersion()))throw version(e.version());int next=e.inputVersion()+1;repository.obsoleteJobs(e.id(),next);UUID analysis=null;if(repository.allActiveSourcesReady(e.id())){analysis=repository.insertJob(e.groupId(),e.id(),null,"ANALYZE",next,"text-edit");if(!processingEnabled)repository.markJobNotConfigured(analysis);}Encounter after=repository.findActive(e.id()).orElseThrow();return response(202,new EncounterDtos.TextUpdated(sourceId,s.textVersion()+1,next,after.version(),analysis));});}
    public EncounterDtos.Binary content(UUID sourceId,UUID userId){Source s=requireActiveSource(sourceId,userId);if(!"DOCUMENT".equals(s.sourceType()))throw new ApiException(HttpStatus.FORBIDDEN,"FORBIDDEN","음성 원본은 제공하지 않습니다.");if(!"AVAILABLE".equals(s.asset().state()))throw notFound();try{StoragePort.StoredObject object=storage.read(s.asset().objectKey());return new EncounterDtos.Binary(s.asset().originalName(),s.asset().mediaType(),object.byteSize(),object.input());}catch(IOException failure){throw notFound();}}
    public IdempotentResult removeSource(UUID encounterId,UUID sourceId,UUID userId,EncounterDtos.VersionRequest request,String key){return idempotency.executeGuarded(userId,"E10:"+sourceId,key,request,()->requireActive(encounterId,userId),()->{Encounter e=repository.lockActive(encounterId);if(e==null)throw notFound();authorize(e,userId);checkVersions(e,request.expectedVersion(),request.expectedInputVersion());Source s=repository.activeSource(sourceId).orElseThrow(this::notFound);if(!s.encounterId().equals(encounterId))throw new ApiException(HttpStatus.FORBIDDEN,"NOT_MEMBER","다른 기록의 소스입니다.");Instant now=clock.instant();repository.removeSource(sourceId,now);repository.markDeletePending(s.assetId());repository.bumpInput(encounterId,e.version(),e.inputVersion());int next=e.inputVersion()+1;repository.obsoleteJobs(encounterId,next);queuePendingSources(e.groupId(),encounterId,next);UUID analysis=null;if(repository.hasActiveSource(encounterId)&&repository.allActiveSourcesReady(encounterId)){analysis=repository.insertJob(e.groupId(),encounterId,null,"ANALYZE",next,"source-remove");if(!processingEnabled)repository.markJobNotConfigured(analysis);}Encounter after=repository.findActive(encounterId).orElseThrow();return response(202,new EncounterDtos.SourceRemoved(encounterId,sourceId,next,after.version(),"DELETE_PENDING",analysis));});}

    public EncounterDtos.Items<EncounterDtos.Job> jobs(UUID encounterId,UUID userId,Integer inputVersion){Encounter e=requireActive(encounterId,userId);int version=inputVersion==null?e.inputVersion():inputVersion;if(version<1)throw validation("inputVersion이 올바르지 않습니다.");return new EncounterDtos.Items<>(repository.jobs(encounterId,version).stream().map(this::jobDto).toList());}
    public EncounterDtos.Job job(UUID jobId,UUID userId){Job job=requireJob(jobId,userId);return jobDto(job);}
    public IdempotentResult retry(UUID jobId,UUID userId,EncounterDtos.RetryRequest request,String key){return idempotency.executeGuarded(userId,"E13:"+jobId,key,request,()->requireJob(jobId,userId),()->{Job job=requireJob(jobId,userId);Encounter e=requireActive(job.encounterId(),userId);if(e.inputVersion()!=request.expectedInputVersion())throw version(e.version());if(!repository.retry(jobId,request.expectedInputVersion()))throw new ApiException(HttpStatus.CONFLICT,"JOB_NOT_RETRYABLE","현재 작업은 재시도할 수 없습니다.");return response(202,jobDto(repository.job(jobId).orElseThrow()));});}

    public EncounterDtos.DeletionPreview deletionPreview(UUID id,UUID userId,EncounterDtos.DeletionPreviewRequest request){Encounter e=requireActive(id,userId);if(e.version()!=request.expectedVersion())throw version(e.version());DeletionImpact impact=repository.deletionImpact(id);String payload=fingerprints.of(request),state=fingerprints.of(List.of(e.version(),e.inputVersion(),impact.fingerprintParts()));String operation="E15:"+id;String token=previews.issue(userId,operation,payload,state);var claims=previews.verify(token,userId,operation,payload);return new EncounterDtos.DeletionPreview(token,claims.expiresAt(),e.version(),impact.sourceIds(),impact.cancelOccurrenceIds(),impact.retainSharedOccurrenceIds(),impact.medicationIds(),true);}
    public IdempotentResult delete(UUID id,UUID userId,EncounterDtos.DeleteRequest request,String key){return idempotency.executeGuarded(userId,"E15:"+id,key,request,()->requireActive(id,userId),()->{Encounter e=repository.lockActive(id);if(e==null)throw notFound();authorize(e,userId);if(e.version()!=request.expectedVersion())throw version(e.version());DeletionImpact impact=repository.deletionImpact(id);String payload=fingerprints.of(new EncounterDtos.DeletionPreviewRequest(request.expectedVersion()));var claims=previews.verify(request.previewToken(),userId,"E15:"+id,payload);String state=fingerprints.of(List.of(e.version(),e.inputVersion(),impact.fingerprintParts()));if(!claims.stateFingerprint().equals(state))throw new ApiException(HttpStatus.CONFLICT,"PREVIEW_STALE","삭제 영향이 변경되었습니다.");repository.acceptDeletion(id,clock.instant());repository.applyDeletionImpact(id,impact.medicationIds(),impact.cancelOccurrenceIds(),impact.retainSharedOccurrenceIds());repository.purgeDeletedSensitive(id);return response(202,new EncounterDtos.DeletionAccepted(id,true,!impact.sourceIds().isEmpty()));});}

    private EncounterDtos.Encounter toEncounter(Encounter e){Revision r=repository.currentRevision(e.id()).orElse(null);boolean stale=r!=null&&r.inputVersion()!=e.inputVersion();return new EncounterDtos.Encounter(e.id(),e.groupId(),e.recordType(),e.title(),e.occurredOn(),e.hospitalName(),new UserRef(e.createdBy(),e.creatorName()),e.inputVersion(),e.version(),e.createdAt(),state(e),repository.hasReviewItems(e.id()),stale);}
    private String state(Encounter e){if(!repository.hasActiveSource(e.id()))return "EMPTY";if(repository.anyActiveSourceFailed(e.id()))return "FAILED";List<Job> jobs=repository.jobs(e.id(),e.inputVersion());if(jobs.stream().anyMatch(j->"TRANSCRIBE".equals(j.jobType())&&List.of("QUEUED","RUNNING").contains(j.status())))return "TRANSCRIBING";if(jobs.stream().anyMatch(j->"OCR".equals(j.jobType())&&List.of("QUEUED","RUNNING").contains(j.status())))return "OCR_PROCESSING";if(jobs.stream().anyMatch(j->"FAILED".equals(j.status())))return "FAILED";if(jobs.stream().anyMatch(j->"ANALYZE".equals(j.jobType())&&List.of("QUEUED","RUNNING").contains(j.status())))return "ANALYZING";return repository.hasReviewItems(e.id())?"NEEDS_REVIEW":"READY";}
    private EncounterDtos.Source sourceDto(Source s){var a=s.asset();return new EncounterDtos.Source(s.id(),s.encounterId(),s.sourceType(),s.status(),s.textVersion(),s.removedAt(),new EncounterDtos.FileRef(a.id(),a.originalName(),a.mediaType(),a.byteSize(),a.state(),null),"DOCUMENT".equals(s.sourceType())&&"AVAILABLE".equals(a.state())?"/api/v1/sources/"+s.id()+"/content":null,s.documentType());}
    private EncounterDtos.Job jobDto(Job j){boolean retryable=repository.canRetry(j);EncounterDtos.JobError error=j.errorCode()==null?null:new EncounterDtos.JobError(j.errorCode(),errorMessage(j.errorCode()),retryable,retryable?"잠시 후 다시 시도해주세요.":"입력 또는 서버 설정을 확인해주세요.");return new EncounterDtos.Job(j.id(),j.encounterId(),j.sourceId(),j.jobType(),j.inputVersion(),j.status(),j.attemptCount(),error,retryable);}
    private List<Job> queuePendingSources(UUID groupId,UUID encounterId,int inputVersion){List<Job> result=new ArrayList<>();for(Source source:repository.sources(encounterId))if("PENDING".equals(source.status())&&"AVAILABLE".equals(source.asset().state())){UUID id=repository.insertJob(groupId,encounterId,source.id(),"AUDIO".equals(source.sourceType())?"TRANSCRIBE":"OCR",inputVersion,"input");if(!processingEnabled)repository.markJobNotConfigured(id);result.add(repository.job(id).orElseThrow());}return result;}
    private EncounterDtos.Summary summary(Revision r){return new EncounterDtos.Summary(r.id(),r.inputVersion(),r.summary()==null||r.summary().isBlank()?null:r.summary(),readJson(r.details()),readJson(r.evidence()));}
    private Object reviewDto(ReviewItem i){Map<String,Object> value=new java.util.LinkedHashMap<>();value.put("id",i.id());value.put("encounterId",i.encounterId());value.put("revisionId",i.revisionId());value.put("itemType",i.itemType());value.put("reviewState",i.reviewState());value.put("reviewReasons",List.of(i.reviewReasons()));value.put("payload",readJson(i.payload()));value.put("evidence",readJson(i.evidence()));value.put("reviewedBy",i.reviewedBy()==null?null:new UserRef(i.reviewedBy(),i.reviewerName()));value.put("reviewedAt",i.reviewedAt());value.put("version",i.version());return value;}
    private Object readJson(String value){try{return json.readTree(value);}catch(RuntimeException e){return Map.of();}}
    private MutationResponse response(int status,Object body){return new MutationResponse(status,DataResponse.of(body));}
    private Encounter requireActive(UUID id,UUID user){Encounter any=repository.find(id).orElseThrow(this::notFound);authorize(any,user);if(any.deletedAt()!=null)throw notFound();return any;}
    private Source requireActiveSource(UUID id,UUID user){Source any=repository.source(id).orElseThrow(this::notFound);Encounter e=repository.find(any.encounterId()).orElseThrow(this::notFound);authorize(e,user);if(e.deletedAt()!=null||any.removedAt()!=null)throw notFound();return any;}
    private Job requireJob(UUID id,UUID user){Job j=repository.job(id).orElseThrow(this::notFound);requireActive(j.encounterId(),user);return j;}
    private GroupMember requireGroup(UUID id,UUID user){groups.findGroup(id).orElseThrow(this::notFound);return groups.findActiveMembership(id,user).orElseThrow(()->new ApiException(HttpStatus.FORBIDDEN,"NOT_MEMBER","공동체의 ACTIVE 구성원이 아닙니다."));}
    private void authorize(Encounter e,UUID user){requireGroup(e.groupId(),user);}
    private void checkVersions(Encounter e,long expected,int input){if(e.version()!=expected||e.inputVersion()!=input)throw version(e.version());}
    private void validateType(String type){if(!List.of("VISIT","DOCUMENT").contains(type))throw validation("recordType이 올바르지 않습니다.");}
    private int limit(Integer value){if(value==null)return 20;if(value<1||value>100)throw validation("limit은 1~100이어야 합니다.");return value;}
    private String encodeEncounterCursor(Encounter e){String raw=(e.occurredOn()==null?"~":e.occurredOn().toString())+"|"+e.createdAt()+"|"+e.id();return java.util.Base64.getUrlEncoder().withoutPadding().encodeToString(raw.getBytes(java.nio.charset.StandardCharsets.UTF_8));}
    private EncounterCursor decodeEncounterCursor(String value){if(value==null||value.isBlank())return null;try{String[] p=new String(java.util.Base64.getUrlDecoder().decode(value),java.nio.charset.StandardCharsets.UTF_8).split("\\|",-1);if(p.length!=3)throw new IllegalArgumentException();return new EncounterCursor("~".equals(p[0])?null:LocalDate.parse(p[0]),Instant.parse(p[1]),UUID.fromString(p[2]));}catch(RuntimeException e){throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_CURSOR","커서가 올바르지 않습니다.");}}
    private String errorMessage(String code){return switch(code){case "AI_NOT_CONFIGURED"->"AI 처리 공급자가 연결되지 않았습니다.";case "AI_INPUT_LIMIT_EXCEEDED"->"입력 제한으로 처리하지 못했습니다.";default->"작업 처리에 실패했습니다.";};}
    private String textNode(tools.jackson.databind.JsonNode node,boolean nullable,String field){if(node.isNull()){if(nullable)return null;throw validation(field+"은 null일 수 없습니다.");}if(!node.isTextual())throw validation(field+" 형식이 올바르지 않습니다.");String value=node.asText();if(value.isBlank()||value.length()>("title".equals(field)?150:150))throw validation(field+" 값을 확인해주세요.");return value;}
    private LocalDate dateNode(tools.jackson.databind.JsonNode node,String field){if(node.isNull())return null;if(!node.isTextual())throw validation(field+" 형식이 올바르지 않습니다.");try{return LocalDate.parse(node.asText());}catch(RuntimeException e){throw validation(field+" 형식이 올바르지 않습니다.");}}
    private void deleteQuietly(Promoted p){try{storage.delete(p.key());}catch(IOException ignored){}}
    private ApiException notFound(){return new ApiException(HttpStatus.NOT_FOUND,"RESOURCE_NOT_FOUND","요청한 리소스를 찾을 수 없습니다.");}
    private ApiException validation(String message){return new ApiException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR",message);}
    private ApiException invalidState(String message){return new ApiException(HttpStatus.CONFLICT,"INVALID_STATE",message);}
    private ApiException version(long current){return new ApiException(HttpStatus.CONFLICT,"VERSION_CONFLICT","기록이 변경되었습니다.",Map.of("currentVersion",current));}
    private record Promoted(ValidatedUpload upload,String key){ }
    private record EncounterCursor(LocalDate occurredOn,Instant createdAt,UUID id){ }
}
