package com.kw.knowone.encounter.controller;

import java.time.LocalDate;import java.util.List;import java.util.UUID;
import org.springframework.core.io.InputStreamResource;import org.springframework.format.annotation.DateTimeFormat;import org.springframework.http.CacheControl;import org.springframework.http.ContentDisposition;import org.springframework.http.HttpHeaders;import org.springframework.http.MediaType;import org.springframework.http.ResponseEntity;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;
import com.kw.knowone.auth.security.AuthenticatedUser;import com.kw.knowone.common.idempotency.IdempotentResult;import com.kw.knowone.common.web.DataResponse;import com.kw.knowone.encounter.dto.EncounterDtos;import com.kw.knowone.encounter.service.EncounterService;import jakarta.validation.Valid;

@RestController @RequestMapping("/api/v1")
public class EncounterController {
    private final EncounterService service;public EncounterController(EncounterService service){this.service=service;}
    @PostMapping("/care-groups/{groupId}/encounters") ResponseEntity<String> create(@PathVariable UUID groupId,@Valid @RequestBody EncounterDtos.CreateRequest body,@RequestHeader(value="Idempotency-Key",required=false)String key,@AuthenticationPrincipal AuthenticatedUser user){return response(service.create(groupId,user.userId(),body,key));}
    @GetMapping("/care-groups/{groupId}/encounters") DataResponse<EncounterDtos.Page<EncounterDtos.Encounter>> list(@PathVariable UUID groupId,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate fromDate,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate toDateExclusive,@RequestParam(required=false)String recordType,@RequestParam(required=false)Integer limit,@RequestParam(required=false)String cursor,@AuthenticationPrincipal AuthenticatedUser user){return DataResponse.of(service.list(groupId,user.userId(),fromDate,toDateExclusive,recordType,limit,cursor));}
    @GetMapping("/encounters/{id}") DataResponse<EncounterDtos.Detail> detail(@PathVariable UUID id,@AuthenticationPrincipal AuthenticatedUser user){return DataResponse.of(service.detail(id,user.userId()));}
    @PatchMapping("/encounters/{id}") ResponseEntity<String> update(@PathVariable UUID id,@Valid @RequestBody EncounterDtos.UpdateRequest body,@RequestHeader(value="Idempotency-Key",required=false)String key,@AuthenticationPrincipal AuthenticatedUser user){return response(service.update(id,user.userId(),body,key));}
    @PostMapping(value="/encounters/{id}/documents",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) ResponseEntity<String> documents(@PathVariable UUID id,@Valid @RequestPart("metadata")EncounterDtos.UploadMetadata metadata,@RequestPart("files")List<MultipartFile> files,@RequestHeader(value="Idempotency-Key",required=false)String key,@AuthenticationPrincipal AuthenticatedUser user){return response(service.uploadDocuments(id,user.userId(),metadata,files,key));}
    @PostMapping(value="/encounters/{id}/audio",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) ResponseEntity<String> audio(@PathVariable UUID id,@Valid @RequestPart("metadata")EncounterDtos.UploadMetadata metadata,@RequestPart("file")MultipartFile file,@RequestHeader(value="Idempotency-Key",required=false)String key,@AuthenticationPrincipal AuthenticatedUser user){return response(service.uploadAudio(id,user.userId(),metadata,file,key));}
    @GetMapping("/sources/{id}/text") DataResponse<EncounterDtos.Text> text(@PathVariable UUID id,@AuthenticationPrincipal AuthenticatedUser user){return DataResponse.of(service.text(id,user.userId()));}
    @PatchMapping("/sources/{id}/text") ResponseEntity<String> textUpdate(@PathVariable UUID id,@Valid @RequestBody EncounterDtos.TextUpdate body,@RequestHeader(value="Idempotency-Key",required=false)String key,@AuthenticationPrincipal AuthenticatedUser user){return response(service.updateText(id,user.userId(),body,key));}
    @GetMapping("/sources/{id}/content") ResponseEntity<InputStreamResource> content(@PathVariable UUID id,@AuthenticationPrincipal AuthenticatedUser user){EncounterDtos.Binary value=service.content(id,user.userId());ContentDisposition disposition=ContentDisposition.inline().filename(value.originalName(),java.nio.charset.StandardCharsets.UTF_8).build();return ResponseEntity.ok().cacheControl(CacheControl.noStore()).header(HttpHeaders.CONTENT_DISPOSITION,disposition.toString()).header("X-Content-Type-Options","nosniff").contentType(MediaType.parseMediaType(value.mediaType())).contentLength(value.byteSize()).body(new InputStreamResource(value.input()));}
    @DeleteMapping("/encounters/{encounterId}/sources/{sourceId}") ResponseEntity<String> removeSource(@PathVariable UUID encounterId,@PathVariable UUID sourceId,@Valid @RequestBody EncounterDtos.VersionRequest body,@RequestHeader(value="Idempotency-Key",required=false)String key,@AuthenticationPrincipal AuthenticatedUser user){return response(service.removeSource(encounterId,sourceId,user.userId(),body,key));}
    @GetMapping("/encounters/{id}/jobs") DataResponse<EncounterDtos.Items<EncounterDtos.Job>> jobs(@PathVariable UUID id,@RequestParam(required=false)Integer inputVersion,@AuthenticationPrincipal AuthenticatedUser user){return DataResponse.of(service.jobs(id,user.userId(),inputVersion));}
    @GetMapping("/processing-jobs/{id}") DataResponse<EncounterDtos.Job> job(@PathVariable UUID id,@AuthenticationPrincipal AuthenticatedUser user){return DataResponse.of(service.job(id,user.userId()));}
    @PostMapping("/processing-jobs/{id}/retry") ResponseEntity<String> retry(@PathVariable UUID id,@Valid @RequestBody EncounterDtos.RetryRequest body,@RequestHeader(value="Idempotency-Key",required=false)String key,@AuthenticationPrincipal AuthenticatedUser user){return response(service.retry(id,user.userId(),body,key));}
    @PostMapping("/encounters/{id}/deletion-preview") DataResponse<EncounterDtos.DeletionPreview> deletionPreview(@PathVariable UUID id,@Valid @RequestBody EncounterDtos.DeletionPreviewRequest body,@AuthenticationPrincipal AuthenticatedUser user){return DataResponse.of(service.deletionPreview(id,user.userId(),body));}
    @DeleteMapping("/encounters/{id}") ResponseEntity<String> delete(@PathVariable UUID id,@Valid @RequestBody EncounterDtos.DeleteRequest body,@RequestHeader(value="Idempotency-Key",required=false)String key,@AuthenticationPrincipal AuthenticatedUser user){return response(service.delete(id,user.userId(),body,key));}
    private ResponseEntity<String> response(IdempotentResult value){return ResponseEntity.status(value.status()).contentType(MediaType.APPLICATION_JSON).body(value.body());}
}
