package com.kw.knowone;

import static org.junit.jupiter.api.Assertions.*;
import java.awt.image.BufferedImage;import java.io.ByteArrayInputStream;import java.io.ByteArrayOutputStream;import java.net.URI;import java.net.http.HttpClient;import java.net.http.HttpRequest;import java.net.http.HttpResponse;import java.nio.charset.StandardCharsets;import java.nio.file.Files;import java.nio.file.Path;import java.util.List;import java.util.UUID;import java.util.concurrent.CompletableFuture;
import javax.imageio.ImageIO;import javax.sound.sampled.AudioFileFormat;import javax.sound.sampled.AudioFormat;import javax.sound.sampled.AudioInputStream;import javax.sound.sampled.AudioSystem;
import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.beans.factory.annotation.Value;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.HttpHeaders;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.mock.web.MockMultipartFile;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.context.DynamicPropertyRegistry;import org.springframework.test.context.DynamicPropertySource;import org.springframework.test.context.jdbc.Sql;
import org.springframework.transaction.support.TransactionTemplate;
import com.kw.knowone.common.web.ApiException;import com.kw.knowone.encounter.dto.EncounterDtos;import com.kw.knowone.encounter.entity.EncounterModels.Job;import com.kw.knowone.encounter.repository.EncounterRepository;import com.kw.knowone.encounter.service.EncounterProcessingWorker;import com.kw.knowone.encounter.service.EncounterService;import com.kw.knowone.encounter.service.FileDeletionWorker;import com.kw.knowone.encounter.service.ProcessingJobTransactions;import tools.jackson.databind.JsonNode;import tools.jackson.databind.ObjectMapper;

@ActiveProfiles("test") @SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
@Sql(scripts={"classpath:phase2-fixture.sql","classpath:phase3-fixture.sql"},executionPhase=Sql.ExecutionPhase.BEFORE_TEST_METHOD)
class Phase5IntegrationTests {
    static final UUID GROUP=UUID.fromString("10000000-0000-4000-8000-000000000001"),CAREGIVER=UUID.fromString("00000000-0000-4000-8000-000000000002"),OUTSIDER=UUID.fromString("00000000-0000-4000-8000-000000000006");
    static final Path FILE_ROOT;static{try{FILE_ROOT=Files.createTempDirectory("phase5-private-");}catch(Exception e){throw new ExceptionInInitializerError(e);}}
    @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("app.storage.local-root",()->FILE_ROOT.toString());r.add("app.encounter.worker-enabled",()->"true");r.add("app.encounter.worker-delay",()->"3600000");r.add("app.encounter.delete-worker-delay",()->"3600000");}
    @Value("${local.server.port}")int port;@Autowired EncounterService service;@Autowired EncounterRepository repository;@Autowired EncounterProcessingWorker worker;@Autowired ProcessingJobTransactions jobs;@Autowired FileDeletionWorker deletionWorker;@Autowired JdbcTemplate jdbc;@Autowired ObjectMapper json;@Autowired TransactionTemplate transaction;final HttpClient client=HttpClient.newHttpClient();

    @Test void encounterCrudUsesRealRowsAndMetadataDoesNotChangeInputVersion()throws Exception{
        String token=login("demo-caregiver-1");JsonNode created=create(token,"VISIT","진료");UUID id=UUID.fromString(created.get("id").asText());
        assertEquals(1,created.get("inputVersion").asInt());assertEquals("EMPTY",created.get("processingState").asText());
        HttpResponse<String> updated=send("PATCH","/api/v1/encounters/"+id,"{\"expectedVersion\":0,\"title\":\"수정\"}",token,"meta");assertEquals(200,updated.statusCode(),updated.body());assertEquals(1,data(updated).get("inputVersion").asInt());
        assertEquals(1,data(send("GET","/api/v1/care-groups/"+GROUP+"/encounters",null,token,null)).get("items").size());JsonNode detail=data(send("GET","/api/v1/encounters/"+id,null,token,null));assertEquals(id.toString(),detail.get("id").asText());assertFalse(detail.has("encounter"));
        assertEquals(403,assertThrows(ApiException.class,()->service.detail(id,OUTSIDER)).status().value());
    }

    @Test void imageLimitIsLockedAndBatchFailureLeavesNoPartialRows()throws Exception{
        UUID id=UUID.fromString(create(login("demo-caregiver-1"),"DOCUMENT","문서").get("id").asText());List<MockMultipartFile> nine=java.util.stream.IntStream.range(0,9).mapToObj(i->image("p"+i+".png")).toList();
        service.uploadDocuments(id,CAREGIVER,new EncounterDtos.UploadMetadata(0L,1),new java.util.ArrayList<>(nine),"nine");assertEquals(9,repository.activeImageCount(id));
        var meta=new EncounterDtos.UploadMetadata(1L,2);CompletableFuture<Integer> a=CompletableFuture.supplyAsync(()->uploadStatus(id,meta,image("a.png"),"a"));CompletableFuture<Integer> b=CompletableFuture.supplyAsync(()->uploadStatus(id,meta,image("b.png"),"b"));
        assertEquals(List.of(202,409),java.util.stream.Stream.of(a.join(),b.join()).sorted().toList());assertEquals(10,repository.activeImageCount(id));assertEquals(10,jdbc.queryForObject("SELECT count(*) FROM encounter_source WHERE encounter_id=?",Integer.class,id));
        assertThrows(ApiException.class,()->service.uploadDocuments(id,CAREGIVER,new EncounterDtos.UploadMetadata(2L,3),List.of(image("ok.png"),new MockMultipartFile("files","bad.png","image/png","bad".getBytes())),"partial"));assertEquals(10,repository.activeImageCount(id));
    }

    @Test void fakeWorkerCreatesTextAndSummaryAndStaleLeaseCannotWrite()throws Exception{
        UUID id=UUID.fromString(create(login("demo-caregiver-1"),"DOCUMENT","처리").get("id").asText());service.uploadDocuments(id,CAREGIVER,new EncounterDtos.UploadMetadata(0L,1),List.of(image("one.png")),"upload");
        assertEquals(1,worker.runOnce(10));assertEquals("READY",repository.sources(id).getFirst().status());assertEquals(1,worker.runOnce(10));assertNotNull(service.detail(id,CAREGIVER).summary());
        UUID second=UUID.fromString(create(login("demo-caregiver-1"),"DOCUMENT","stale").get("id").asText());service.uploadDocuments(second,CAREGIVER,new EncounterDtos.UploadMetadata(0L,1),List.of(image("old.png")),"old");Job claimed=jobs.claim(1).getFirst();
        service.uploadDocuments(second,CAREGIVER,new EncounterDtos.UploadMetadata(1L,2),List.of(image("new.png")),"new");assertFalse(jobs.completeText(claimed,"늦은 결과"));assertNull(repository.activeSource(claimed.sourceId()).orElseThrow().extractedText());assertEquals("OBSOLETE",repository.job(claimed.id()).orElseThrow().status());
    }

    @Test void idempotentUploadDoesNotDuplicateObjectsJobsAndCrossGroupAccessIsDenied()throws Exception{
        UUID id=UUID.fromString(create(login("demo-caregiver-1"),"DOCUMENT","멱등").get("id").asText());var metadata=new EncounterDtos.UploadMetadata(0L,1);byte[] bytes=image("same.png").getBytes();
        var first=service.uploadDocuments(id,CAREGIVER,metadata,List.of(new MockMultipartFile("files","same.png","image/png",bytes)),"same-upload");long objectCount=countStoredObjects();
        var replay=service.uploadDocuments(id,CAREGIVER,metadata,List.of(new MockMultipartFile("files","same.png","image/png",bytes)),"same-upload");assertFalse(first.replayed());assertTrue(replay.replayed());
        assertEquals(1,jdbc.queryForObject("SELECT count(*) FROM encounter_source WHERE encounter_id=?",Integer.class,id));assertEquals(1,jdbc.queryForObject("SELECT count(*) FROM processing_job WHERE encounter_id=?",Integer.class,id));assertEquals(objectCount,countStoredObjects());assertEquals(0,countTemporaryObjects());
        UUID source=repository.sources(id).getFirst().id(),job=repository.jobs(id,2).getFirst().id();assertEquals(403,assertThrows(ApiException.class,()->service.text(source,OUTSIDER)).status().value());assertEquals(403,assertThrows(ApiException.class,()->service.content(source,OUTSIDER)).status().value());assertEquals(403,assertThrows(ApiException.class,()->service.job(job,OUTSIDER)).status().value());
    }

    @Test void expiredLeaseGetsNewTokenAndFencesLateWorker()throws Exception{
        UUID id=UUID.fromString(create(login("demo-caregiver-1"),"DOCUMENT","lease").get("id").asText());service.uploadDocuments(id,CAREGIVER,new EncounterDtos.UploadMetadata(0L,1),List.of(image("lease.png")),"lease-upload");Job first=jobs.claim(1).getFirst();
        jdbc.update("UPDATE processing_job SET lease_until=now()-interval '1 second' WHERE id=?",first.id());Job reclaimed=jobs.claim(1).getFirst();assertNotEquals(first.leaseToken(),reclaimed.leaseToken());assertFalse(jobs.completeText(first,"old"));assertTrue(jobs.completeText(reclaimed,"new"));assertEquals("new",repository.activeSource(first.sourceId()).orElseThrow().extractedText());
    }

    @Test void partialSourceFailureBlocksAnalysisUntilRetrySucceeds()throws Exception{
        UUID id=UUID.fromString(create(login("demo-caregiver-1"),"DOCUMENT","부분 실패").get("id").asText());service.uploadDocuments(id,CAREGIVER,new EncounterDtos.UploadMetadata(0L,1),List.of(image("one.png"),image("two.png")),"two-files");List<Job> claimed=jobs.claim(2);assertEquals(2,claimed.size());
        jobs.completeText(claimed.get(0),"준비됨");jobs.fail(claimed.get(1),"AI_PROVIDER_UNAVAILABLE");assertEquals("FAILED",repository.activeSource(claimed.get(1).sourceId()).orElseThrow().status());assertEquals("FAILED",service.detail(id,CAREGIVER).processingState());assertEquals(0,jdbc.queryForObject("SELECT count(*) FROM processing_job WHERE encounter_id=? AND job_type='ANALYZE'",Integer.class,id));
        assertTrue(service.job(claimed.get(1).id(),CAREGIVER).canRetry());service.retry(claimed.get(1).id(),CAREGIVER,new EncounterDtos.RetryRequest(2),"retry-source");assertEquals("PENDING",repository.activeSource(claimed.get(1).sourceId()).orElseThrow().status());assertEquals(1,worker.runOnce(10));assertEquals(1,worker.runOnce(10));assertNotNull(service.detail(id,CAREGIVER).summary());
    }

    @Test void analyzeRetryReusesStoredSourceTextAndKeepsSingleRevision()throws Exception{
        UUID id=UUID.fromString(create(login("demo-caregiver-1"),"DOCUMENT","요약 재시도").get("id").asText());service.uploadDocuments(id,CAREGIVER,new EncounterDtos.UploadMetadata(0L,1),List.of(image("summary.png")),"summary-upload");worker.runOnce(10);Job analysis=jobs.claim(1).getFirst();assertEquals("ANALYZE",analysis.jobType());jobs.fail(analysis,"AI_TIMEOUT");String stored=repository.sources(id).getFirst().extractedText();
        service.retry(analysis.id(),CAREGIVER,new EncounterDtos.RetryRequest(2),"retry-analysis");worker.runOnce(10);assertEquals(stored,repository.sources(id).getFirst().extractedText());assertEquals(1,jdbc.queryForObject("SELECT count(*) FROM encounter_revision WHERE encounter_id=?",Integer.class,id));assertTrue(repository.currentRevision(id).isPresent());
    }

    @Test void sourceRemovalAndTranscriptEditFenceOlderWork()throws Exception{
        UUID document=UUID.fromString(create(login("demo-caregiver-1"),"DOCUMENT","제거 경쟁").get("id").asText());service.uploadDocuments(document,CAREGIVER,new EncounterDtos.UploadMetadata(0L,1),List.of(image("remove.png")),"remove-upload");Job ocr=jobs.claim(1).getFirst();UUID source=ocr.sourceId();var removed=service.removeSource(document,source,CAREGIVER,new EncounterDtos.VersionRequest(1L,2),"remove-source");assertEquals(202,removed.status());assertFalse(jobs.completeText(ocr,"늦은 OCR"));assertEquals("EMPTY",service.detail(document,CAREGIVER).processingState());assertTrue(repository.jobs(document,3).isEmpty());
        UUID audio=UUID.fromString(create(login("demo-caregiver-1"),"VISIT","전사 수정 경쟁").get("id").asText());service.uploadAudio(audio,CAREGIVER,new EncounterDtos.UploadMetadata(0L,1),new MockMultipartFile("file","edit.wav","audio/wav",wav()),"edit-audio");worker.runOnce(10);UUID audioSource=repository.sources(audio).getFirst().id();Job oldAnalysis=jobs.claim(1).getFirst();var edited=service.updateText(audioSource,CAREGIVER,new EncounterDtos.TextUpdate(2,1,"사용자 교정"),"edit-text");assertEquals(3,json.readTree(edited.body()).get("data").get("inputVersion").asInt());assertFalse(jobs.completeAnalysis(oldAnalysis,new com.kw.knowone.encounter.processing.AiProcessingPort.AnalysisResult("오래된 요약","{}","[]")));assertEquals(1,jdbc.queryForObject("SELECT count(*) FROM processing_job WHERE encounter_id=? AND input_version=3 AND job_type='ANALYZE'",Integer.class,audio));
    }

    @Test void expiredFailedAudioIsDeletedAndDeleteFailureRemainsRetryable()throws Exception{
        UUID audio=UUID.fromString(create(login("demo-caregiver-1"),"VISIT","만료 음성").get("id").asText());service.uploadAudio(audio,CAREGIVER,new EncounterDtos.UploadMetadata(0L,1),new MockMultipartFile("file","expired.wav","audio/wav",wav()),"expired-audio");Job transcription=jobs.claim(1).getFirst();jobs.fail(transcription,"AI_PROVIDER_UNAVAILABLE");UUID audioAsset=repository.sources(audio).getFirst().assetId();jdbc.update("UPDATE file_asset SET expires_at=now()-interval '1 second' WHERE id=?",audioAsset);deletionWorker.runOnce(10);assertEquals("DELETED",jdbc.queryForObject("SELECT state FROM file_asset WHERE id=?",String.class,audioAsset));
        UUID document=UUID.fromString(create(login("demo-caregiver-1"),"DOCUMENT","삭제 재시도").get("id").asText());service.uploadDocuments(document,CAREGIVER,new EncounterDtos.UploadMetadata(0L,1),List.of(image("retry-delete.png")),"retry-delete-upload");var source=repository.sources(document).getFirst();String realKey=source.asset().objectKey();service.removeSource(document,source.id(),CAREGIVER,new EncounterDtos.VersionRequest(1L,2),"retry-delete-source");jdbc.update("UPDATE file_asset SET object_key='../escape' WHERE id=?",source.assetId());deletionWorker.runOnce(10);assertEquals("DELETE_PENDING",jdbc.queryForObject("SELECT state FROM file_asset WHERE id=?",String.class,source.assetId()));assertEquals(1,jdbc.queryForObject("SELECT delete_attempts FROM file_asset WHERE id=?",Integer.class,source.assetId()));jdbc.update("UPDATE file_asset SET object_key=? WHERE id=?",realKey,source.assetId());deletionWorker.runOnce(10);assertEquals("DELETED",jdbc.queryForObject("SELECT state FROM file_asset WHERE id=?",String.class,source.assetId()));
    }

    @Test void audioTranscriptionSchedulesAndPhysicallyDeletesOriginal()throws Exception{
        UUID id=UUID.fromString(create(login("demo-caregiver-1"),"VISIT","음성").get("id").asText());service.uploadAudio(id,CAREGIVER,new EncounterDtos.UploadMetadata(0L,1),new MockMultipartFile("file","voice.wav","audio/wav",wav()),"audio");UUID asset=repository.sources(id).getFirst().assetId();
        worker.runOnce(10);assertEquals("DELETE_PENDING",repository.sourceByAsset(asset).orElseThrow().asset().state());deletionWorker.runOnce(10);assertEquals("DELETED",jdbc.queryForObject("SELECT state FROM file_asset WHERE id=?",String.class,asset));assertNull(jdbc.queryForObject("SELECT object_key FROM file_asset WHERE id=?",String.class,asset));
    }

    @Test void deletionBlocksAccessImmediatelyThenPurgesSensitiveText()throws Exception{
        String token=login("demo-caregiver-1");UUID id=UUID.fromString(create(token,"DOCUMENT","삭제").get("id").asText());service.uploadDocuments(id,CAREGIVER,new EncounterDtos.UploadMetadata(0L,1),List.of(image("delete.png")),"delete-upload");worker.runOnce(10);UUID source=repository.sources(id).getFirst().id();
        worker.runOnce(10);UUID[] linked=linkedMedicationFixtures(id);
        EncounterDtos.DeletionPreview preview=service.deletionPreview(id,CAREGIVER,new EncounterDtos.DeletionPreviewRequest(1L));assertTrue(preview.retainSharedOccurrenceIds().contains(linked[0]));assertTrue(preview.cancelOccurrenceIds().contains(linked[1]));service.delete(id,CAREGIVER,new EncounterDtos.DeleteRequest(1L,preview.previewToken()),"delete");
        assertEquals(404,send("GET","/api/v1/encounters/"+id,null,token,null).statusCode());assertEquals(404,send("GET","/api/v1/sources/"+source+"/text",null,token,null).statusCode());deletionWorker.runOnce(10);assertNull(jdbc.queryForObject("SELECT extracted_text FROM encounter_source WHERE id=?",String.class,source));
        assertEquals("PENDING",jdbc.queryForObject("SELECT status FROM task_occurrence WHERE id=?",String.class,linked[0]));assertEquals(1,jdbc.queryForObject("SELECT count(*) FROM occurrence_medication WHERE occurrence_id=?",Integer.class,linked[0]));assertEquals("CANCELED",jdbc.queryForObject("SELECT status FROM task_occurrence WHERE id=?",String.class,linked[1]));assertEquals("RECORD_DELETED",jdbc.queryForObject("SELECT cancel_reason FROM task_occurrence WHERE id=?",String.class,linked[1]));
    }

    private int uploadStatus(UUID id,EncounterDtos.UploadMetadata meta,MockMultipartFile file,String key){try{return service.uploadDocuments(id,CAREGIVER,meta,List.of(file),key).status();}catch(ApiException e){return e.status().value();}}
    private long countStoredObjects()throws Exception{Path objects=FILE_ROOT.resolve("objects");if(!Files.exists(objects))return 0;try(var paths=Files.walk(objects)){return paths.filter(Files::isRegularFile).count();}}
    private long countTemporaryObjects()throws Exception{Path tmp=FILE_ROOT.resolve("tmp");if(!Files.exists(tmp))return 0;try(var paths=Files.list(tmp)){return paths.filter(Files::isRegularFile).count();}}
    private MockMultipartFile image(String name){try{ByteArrayOutputStream out=new ByteArrayOutputStream();ImageIO.write(new BufferedImage(2,2,BufferedImage.TYPE_INT_RGB),"png",out);return new MockMultipartFile("files",name,"image/png",out.toByteArray());}catch(Exception e){throw new RuntimeException(e);}}
    private byte[] wav()throws Exception{AudioFormat format=new AudioFormat(8000,16,1,true,false);byte[] pcm=new byte[1600];try(AudioInputStream in=new AudioInputStream(new ByteArrayInputStream(pcm),format,pcm.length/format.getFrameSize());ByteArrayOutputStream out=new ByteArrayOutputStream()){AudioSystem.write(in,AudioFileFormat.Type.WAVE,out);return out.toByteArray();}}
    private UUID[] linkedMedicationFixtures(UUID encounterId){return transaction.execute(status->{jdbc.execute("SET CONSTRAINTS ALL DEFERRED");UUID revision=jdbc.queryForObject("SELECT id FROM encounter_revision WHERE encounter_id=? AND is_current",UUID.class,encounterId);UUID currentItem=UUID.randomUUID(),currentMedication=UUID.randomUUID();jdbc.update("INSERT INTO extracted_item(id,group_id,encounter_id,revision_id,item_key,item_type,payload,review_state,application_key,applied_at) VALUES (?,?,?,?,?,'MEDICATION','{}','APPLIED',?,now())",currentItem,GROUP,encounterId,revision,"current-med","applied:"+currentItem);jdbc.update("INSERT INTO medication_order(id,group_id,source_item_id,name,dose_text,frequency_text,starts_on,ends_on,confirmed_by) VALUES (?,?,?,'가상 현재약','1정','1회',current_date,current_date+10,?)",currentMedication,GROUP,currentItem,CAREGIVER);
        UUID otherEncounter=UUID.randomUUID(),otherJob=UUID.randomUUID(),otherRevision=UUID.randomUUID(),otherItem=UUID.randomUUID(),otherMedication=UUID.randomUUID();jdbc.update("INSERT INTO encounter(id,group_id,created_by,record_type,title) VALUES (?,?,?,'DOCUMENT','다른 기록')",otherEncounter,GROUP,CAREGIVER);jdbc.update("INSERT INTO processing_job(id,group_id,encounter_id,job_type,input_version,dedup_key,status) VALUES (?,?,?,'ANALYZE',1,?,'SUCCEEDED')",otherJob,GROUP,otherEncounter,"other:"+otherJob);jdbc.update("INSERT INTO encounter_revision(id,group_id,encounter_id,input_version,job_id,summary,is_current) VALUES (?,?,?,?,?,'다른 요약',true)",otherRevision,GROUP,otherEncounter,1,otherJob);jdbc.update("INSERT INTO extracted_item(id,group_id,encounter_id,revision_id,item_key,item_type,payload,review_state,application_key,applied_at) VALUES (?,?,?,?,?,'MEDICATION','{}','APPLIED',?,now())",otherItem,GROUP,otherEncounter,otherRevision,"other-med","applied:"+otherItem);jdbc.update("INSERT INTO medication_order(id,group_id,source_item_id,name,dose_text,frequency_text,starts_on,ends_on,confirmed_by) VALUES (?,?,?,'가상 다른약','1정','1회',current_date,current_date+10,?)",otherMedication,GROUP,otherItem,CAREGIVER);
        UUID shared=taskWithMedications(currentMedication,otherMedication,"공유 업무"),sole=taskWithMedications(currentMedication,null,"단독 업무");return new UUID[]{shared,sole};});}
    private UUID taskWithMedications(UUID first,UUID second,String title){UUID series=UUID.randomUUID(),occurrence=UUID.randomUUID();jdbc.update("INSERT INTO task_series(id,group_id,kind,created_by,generation_key) VALUES (?,?,'MEDICATION',?,?)",series,GROUP,CAREGIVER,"phase5:"+series);jdbc.update("INSERT INTO task_series_revision(series_id,revision_no,group_id,title,recurrence,first_date,last_date,local_time,duration_minutes,effective_at,changed_by) VALUES (?,1,?,?,'ONCE',current_date+2,current_date+2,'08:00',30,now(),?)",series,GROUP,title,CAREGIVER);jdbc.update("INSERT INTO task_occurrence(id,group_id,series_id,revision_no,anchor_date,title,starts_at,ends_at) VALUES (?,?,?,1,current_date+2,?,now()+interval '2 day',now()+interval '2 day 30 minute')",occurrence,GROUP,series,title);jdbc.update("INSERT INTO occurrence_medication(group_id,occurrence_id,medication_id) VALUES (?,?,?)",GROUP,occurrence,first);if(second!=null)jdbc.update("INSERT INTO occurrence_medication(group_id,occurrence_id,medication_id) VALUES (?,?,?)",GROUP,occurrence,second);return occurrence;}
    private JsonNode create(String token,String type,String title)throws Exception{return data(send("POST","/api/v1/care-groups/"+GROUP+"/encounters","{\"recordType\":\""+type+"\",\"title\":\""+title+"\"}",token,"create-"+UUID.randomUUID()));}
    private String login(String key)throws Exception{return data(send("POST","/api/v1/auth/demo-login","{\"loginKey\":\""+key+"\"}",null,null)).get("accessToken").asText();}
    private JsonNode data(HttpResponse<String> r)throws Exception{assertTrue(r.statusCode()>=200&&r.statusCode()<300,r.body());return json.readTree(r.body()).get("data");}
    private HttpResponse<String> send(String method,String path,String body,String token,String key)throws Exception{HttpRequest.Builder b=HttpRequest.newBuilder(URI.create("http://localhost:"+port+path)).header("Content-Type","application/json");if(token!=null)b.header(HttpHeaders.AUTHORIZATION,"Bearer "+token);if(key!=null)b.header("Idempotency-Key",key);return client.send(b.method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(body,StandardCharsets.UTF_8)).build(),HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));}
}
