package com.kw.knowone;

import static org.junit.jupiter.api.Assertions.*;
import java.time.Clock;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.transaction.support.TransactionTemplate;
import com.kw.knowone.common.web.ApiException;
import com.kw.knowone.review.dto.ReviewDtos;
import com.kw.knowone.review.service.ReviewService;
import com.kw.knowone.encounter.processing.AiProcessingPort.AnalysisItem;
import com.kw.knowone.encounter.processing.AiProcessingPort.AnalysisResult;
import com.kw.knowone.encounter.service.ProcessingJobTransactions;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;

@ActiveProfiles("test") @SpringBootTest
@Sql(scripts={"classpath:phase2-fixture.sql","classpath:phase3-fixture.sql"},executionPhase=Sql.ExecutionPhase.BEFORE_TEST_METHOD)
class Phase6IntegrationTests {
    static final UUID GROUP=UUID.fromString("10000000-0000-4000-8000-000000000001"),CAREGIVER=UUID.fromString("00000000-0000-4000-8000-000000000002"),OUTSIDER=UUID.fromString("00000000-0000-4000-8000-000000000006");
    @Autowired JdbcTemplate jdbc;@Autowired ReviewService reviews;@Autowired ObjectMapper json;@Autowired Clock clock;@Autowired ProcessingJobTransactions jobs;@Autowired TransactionTemplate transaction;LocalDate today;
    @BeforeEach void dates(){today=LocalDate.now(clock);}

    @Test void batchConfirmationCreatesMedicationSeriesAndDateSpecificSnapshots(){Fixture fixture=fixture(2);JsonNode first=med("A약",today.plusDays(1),today.plusDays(4),"08:00");JsonNode second=med("B약",today.plusDays(3),today.plusDays(6),"08:00");
        putPayload(fixture.items().get(0),first);putPayload(fixture.items().get(1),second);ReviewDtos.ConfirmRequest request=new ReviewDtos.ConfirmRequest(1,fixture.revision(),List.of(
                new ReviewDtos.ConfirmItem(fixture.items().get(0),0L,first,null),new ReviewDtos.ConfirmItem(fixture.items().get(1),0L,second,null)));
        var result=reviews.confirm(fixture.encounter(),CAREGIVER,request,"confirm-two");assertEquals(200,result.status());assertFalse(result.replayed());
        assertEquals(2,jdbc.queryForObject("SELECT count(*) FROM medication_order WHERE group_id=?",Integer.class,GROUP));assertEquals(1,jdbc.queryForObject("SELECT count(*) FROM task_series WHERE kind='MEDICATION'",Integer.class));
        assertEquals(2,jdbc.queryForObject("SELECT count(*) FROM audit_event WHERE event_type='MEDICATION_CONFIRMED'",Integer.class));assertEquals(2,jdbc.queryForObject("SELECT count(*) FROM notification_event WHERE event_type='MEDICATION_CONFIRMED'",Integer.class));
        assertEquals(1,jdbc.queryForObject("SELECT count(*) FROM task_occurrence o WHERE o.anchor_date=? AND (SELECT count(*) FROM occurrence_medication om WHERE om.occurrence_id=o.id)=1",Integer.class,today.plusDays(1)));
        assertEquals(1,jdbc.queryForObject("SELECT count(*) FROM task_occurrence o WHERE o.anchor_date=? AND (SELECT count(*) FROM occurrence_medication om WHERE om.occurrence_id=o.id)=2",Integer.class,today.plusDays(3)));
        assertEquals(2,reviews.medications(GROUP,CAREGIVER,fixture.encounter(),null,20,null).items().size());assertEquals(1,reviews.medications(GROUP,CAREGIVER,null,today.plusDays(1),20,null).items().size());assertEquals(403,assertThrows(ApiException.class,()->reviews.medications(GROUP,OUTSIDER,null,null,20,null)).status().value());
        assertTrue(reviews.confirm(fixture.encounter(),CAREGIVER,request,"confirm-two").replayed());assertEquals(2,jdbc.queryForObject("SELECT count(*) FROM medication_order",Integer.class));}

    @Test void staleCandidateVersionRollsBackBeforeAnySideEffect(){Fixture fixture=fixture(1);JsonNode payload=med("경쟁약",today.plusDays(1),today.plusDays(2),"08:00");ApiException error=assertThrows(ApiException.class,()->reviews.confirm(fixture.encounter(),CAREGIVER,new ReviewDtos.ConfirmRequest(1,fixture.revision(),List.of(new ReviewDtos.ConfirmItem(fixture.items().getFirst(),1L,payload,null))),"stale"));assertEquals("VERSION_CONFLICT",error.code());assertEquals(0,jdbc.queryForObject("SELECT count(*) FROM medication_order",Integer.class));assertEquals(0,jdbc.queryForObject("SELECT count(*) FROM notification_event WHERE event_type='MEDICATION_CONFIRMED'",Integer.class));}

    @Test void supersedingPrescriptionChangesOnlyNotYetStartedSnapshots(){UUID old=existingMedicationSeries();Fixture fixture=fixture(1);JsonNode replacement=med("변경약",today.plusDays(1),today.plusDays(3),"08:00");((tools.jackson.databind.node.ObjectNode)replacement).put("supersedesMedicationId",old.toString());putPayload(fixture.items().getFirst(),replacement);
        reviews.confirm(fixture.encounter(),CAREGIVER,new ReviewDtos.ConfirmRequest(1,fixture.revision(),List.of(new ReviewDtos.ConfirmItem(fixture.items().getFirst(),0L,replacement,null))),"replace");
        assertEquals(old,jdbc.queryForObject("SELECT om.medication_id FROM occurrence_medication om JOIN task_occurrence o ON o.id=om.occurrence_id WHERE o.anchor_date=current_date",UUID.class));assertNotEquals(old,jdbc.queryForObject("SELECT om.medication_id FROM occurrence_medication om JOIN task_occurrence o ON o.id=om.occurrence_id WHERE o.anchor_date=current_date+1",UUID.class));}

    @Test void multipleDailyTimesRemainSeparateSeries(){Fixture fixture=fixture(1);JsonNode payload=medWithTimes("C약",today.plusDays(1),today.plusDays(3),List.of("08:00","20:00"));putPayload(fixture.items().getFirst(),payload);
        reviews.confirm(fixture.encounter(),CAREGIVER,new ReviewDtos.ConfirmRequest(1,fixture.revision(),List.of(new ReviewDtos.ConfirmItem(fixture.items().getFirst(),0L,payload,null))),"two-times");
        assertEquals(2,jdbc.queryForObject("SELECT count(*) FROM task_series WHERE kind='MEDICATION'",Integer.class));assertEquals(6,jdbc.queryForObject("SELECT count(*) FROM task_occurrence o JOIN task_series s ON s.id=o.series_id WHERE s.kind='MEDICATION'",Integer.class));}

    @Test void invalidMemberOfBatchRollsEverythingBack(){Fixture fixture=fixture(2);JsonNode valid=med("A약",today.plusDays(1),today.plusDays(2),"09:00"),invalid=med("B약",today.plusDays(1),today.plusDays(2),"09:00");((tools.jackson.databind.node.ObjectNode)invalid).putNull("doseText");
        assertThrows(ApiException.class,()->reviews.confirm(fixture.encounter(),CAREGIVER,new ReviewDtos.ConfirmRequest(1,fixture.revision(),List.of(new ReviewDtos.ConfirmItem(fixture.items().get(0),0L,valid,null),new ReviewDtos.ConfirmItem(fixture.items().get(1),0L,invalid,null))),"rollback"));
        assertEquals(0,jdbc.queryForObject("SELECT count(*) FROM medication_order",Integer.class));assertEquals(2,jdbc.queryForObject("SELECT count(*) FROM extracted_item WHERE review_state='NEEDS_REVIEW'",Integer.class));}

    @Test void duplicateMedicationCandidatesRollbackTheWholeConfirmation(){Fixture fixture=fixture(2);JsonNode same=med("중복약",today.plusDays(1),today.plusDays(2),"09:00");ApiException error=assertThrows(ApiException.class,()->reviews.confirm(fixture.encounter(),CAREGIVER,new ReviewDtos.ConfirmRequest(1,fixture.revision(),List.of(new ReviewDtos.ConfirmItem(fixture.items().get(0),0L,same,null),new ReviewDtos.ConfirmItem(fixture.items().get(1),0L,same.deepCopy(),null))),"duplicates"));assertEquals("DUPLICATE_MEDICATION_CONFLICT",error.code());assertEquals(0,jdbc.queryForObject("SELECT count(*) FROM medication_order",Integer.class));}

    @Test void conflictCannotBeConfirmedWithoutExplicitManualResolution(){Fixture fixture=fixture(1);UUID item=fixture.items().getFirst();JsonNode payload=med("충돌약",today.plusDays(1),today.plusDays(2),"09:00");jdbc.update("UPDATE extracted_item SET payload=CAST(? AS jsonb),review_reasons=ARRAY['CONFLICT'] WHERE id=?",json.writeValueAsString(payload),item);ReviewDtos.ConfirmRequest unresolved=new ReviewDtos.ConfirmRequest(1,fixture.revision(),List.of(new ReviewDtos.ConfirmItem(item,0L,payload,null)));assertEquals("REVIEW_REQUIRED",assertThrows(ApiException.class,()->reviews.confirm(fixture.encounter(),CAREGIVER,unresolved,"unresolved")).code());var resolution=json.createObjectNode();resolution.put("mode","MANUAL");resolution.put("note","가상 원문을 대조함");reviews.confirm(fixture.encounter(),CAREGIVER,new ReviewDtos.ConfirmRequest(1,fixture.revision(),List.of(new ReviewDtos.ConfirmItem(item,0L,payload,resolution))),"resolved");assertEquals(1,jdbc.queryForObject("SELECT count(*) FROM medication_order",Integer.class));}

    @Test void listDismissAndCrossGroupAuthorizationFollowCurrentRevision(){Fixture fixture=fixture(1);assertEquals(1,reviews.items(fixture.encounter(),CAREGIVER,null).items().size());assertEquals(403,assertThrows(ApiException.class,()->reviews.items(fixture.encounter(),OUTSIDER,null)).status().value());
        UUID item=fixture.items().getFirst();reviews.dismiss(fixture.encounter(),item,CAREGIVER,new ReviewDtos.DismissRequest(0L),"dismiss");assertTrue(reviews.items(fixture.encounter(),CAREGIVER,null).items().isEmpty());assertEquals("DISMISSED",reviews.items(fixture.encounter(),CAREGIVER,"ALL").items().getFirst().reviewState());}

    @Test void clearGeneralTaskAutoAppliesButMedicationNeverDoes(){UUID encounter=UUID.randomUUID(),jobId=UUID.randomUUID();jdbc.update("INSERT INTO encounter(id,group_id,created_by,record_type,title,input_version) VALUES (?,?,?,'DOCUMENT','자동 적용',1)",encounter,GROUP,CAREGIVER);
        jdbc.update("INSERT INTO processing_job(id,group_id,encounter_id,job_type,input_version,dedup_key) VALUES (?,?,?,'ANALYZE',1,?)",jobId,GROUP,encounter,"auto:"+jobId);var job=jobs.claim(1).getFirst();
        var task=json.createObjectNode();task.put("schemaVersion",1);task.put("kind","EXAM");task.put("title","명확한 검사");task.putNull("description");task.put("date",today.plusDays(2).toString());task.put("time","11:00");task.put("durationMinutes",30);task.put("durationSource","SOURCE");task.put("recurrence","ONCE");task.put("lastDate",today.plusDays(2).toString());task.putArray("weekdays");
        JsonNode medication=med("확인 약",today.plusDays(1),today.plusDays(3),"08:00");AnalysisResult result=new AnalysisResult(null,"{\"symptoms\":[],\"tests\":[],\"medicationMentions\":[],\"precautions\":[],\"followUps\":[]}","[]",List.of(
                new AnalysisItem("task","TASK",json.writeValueAsString(task),"[]","READY",List.of()),new AnalysisItem("med","MEDICATION",json.writeValueAsString(medication),"[]","NEEDS_REVIEW",List.of("MED_REVIEW"))),"FAKE","fake","1.0",0,0);
        assertTrue(jobs.completeAnalysis(job,result));assertEquals(1,jdbc.queryForObject("SELECT count(*) FROM task_series WHERE source_item_id IS NOT NULL",Integer.class));assertEquals(1,jdbc.queryForObject("SELECT count(*) FROM extracted_item WHERE item_type='TASK' AND review_state='APPLIED'",Integer.class));assertEquals(1,jdbc.queryForObject("SELECT count(*) FROM extracted_item WHERE item_type='MEDICATION' AND review_state='NEEDS_REVIEW'",Integer.class));assertEquals(0,jdbc.queryForObject("SELECT count(*) FROM medication_order",Integer.class));}

    private Fixture fixture(int count){UUID encounter=UUID.randomUUID(),job=UUID.randomUUID(),revision=UUID.randomUUID();jdbc.update("INSERT INTO encounter(id,group_id,created_by,record_type,title,input_version) VALUES (?,?,?,'DOCUMENT','후보',1)",encounter,GROUP,CAREGIVER);
        jdbc.update("INSERT INTO processing_job(id,group_id,encounter_id,job_type,input_version,dedup_key,status) VALUES (?,?,?,'ANALYZE',1,?,'SUCCEEDED')",job,GROUP,encounter,"phase6:"+job);jdbc.update("INSERT INTO encounter_revision(id,group_id,encounter_id,input_version,job_id,summary,is_current) VALUES (?,?,?,?,?,'요약',true)",revision,GROUP,encounter,1,job);
        java.util.ArrayList<UUID> items=new java.util.ArrayList<>();for(int i=0;i<count;i++){UUID item=UUID.randomUUID();items.add(item);jdbc.update("INSERT INTO extracted_item(id,group_id,encounter_id,revision_id,item_key,item_type,payload,review_state) VALUES (?,?,?,?,?,'MEDICATION','{}','NEEDS_REVIEW')",item,GROUP,encounter,revision,"med-"+i);}return new Fixture(encounter,revision,items);}
    private void putPayload(UUID item,JsonNode payload){jdbc.update("UPDATE extracted_item SET payload=CAST(? AS jsonb) WHERE id=?",json.writeValueAsString(payload),item);}
    private UUID existingMedicationSeries(){return transaction.execute(status->{jdbc.execute("SET CONSTRAINTS ALL DEFERRED");UUID encounter=UUID.randomUUID(),job=UUID.randomUUID(),revision=UUID.randomUUID(),item=UUID.randomUUID(),medication=UUID.randomUUID(),series=UUID.randomUUID(),todayOccurrence=UUID.randomUUID(),tomorrowOccurrence=UUID.randomUUID();jdbc.update("INSERT INTO encounter(id,group_id,created_by,record_type,title) VALUES (?,?,?,'DOCUMENT','이전 처방')",encounter,GROUP,CAREGIVER);jdbc.update("INSERT INTO processing_job(id,group_id,encounter_id,job_type,input_version,dedup_key,status) VALUES (?,?,?,'ANALYZE',1,?,'SUCCEEDED')",job,GROUP,encounter,"old:"+job);jdbc.update("INSERT INTO encounter_revision(id,group_id,encounter_id,input_version,job_id,summary,is_current) VALUES (?,?,?,?,?,'이전',true)",revision,GROUP,encounter,1,job);jdbc.update("INSERT INTO extracted_item(id,group_id,encounter_id,revision_id,item_key,item_type,payload,review_state,application_key,applied_at) VALUES (?,?,?,?,?,'MEDICATION','{}','APPLIED',?,now())",item,GROUP,encounter,revision,"old", "old:"+item);jdbc.update("INSERT INTO medication_order(id,group_id,source_item_id,name,dose_text,frequency_text,starts_on,ends_on,confirmed_by) VALUES (?,?,?,'이전약','1정','하루 1회',current_date,current_date+3,?)",medication,GROUP,item,CAREGIVER);jdbc.update("INSERT INTO task_series(id,group_id,kind,created_by,generation_key) VALUES (?,?,'MEDICATION',?,'old-series')",series,GROUP,CAREGIVER);jdbc.update("INSERT INTO task_series_revision(series_id,revision_no,group_id,title,recurrence,first_date,last_date,local_time,duration_minutes,effective_at,changed_by) VALUES (?,1,?,'08:00 복약 챙기기','DAILY',current_date,current_date+3,'08:00',30,now(),?)",series,GROUP,CAREGIVER);jdbc.update("INSERT INTO series_medication(group_id,series_id,revision_no,medication_id) VALUES (?,?,1,?)",GROUP,series,medication);jdbc.update("INSERT INTO task_occurrence(id,group_id,series_id,revision_no,anchor_date,title,starts_at,ends_at) VALUES (?,?,?,1,current_date,'08:00 복약 챙기기',now()-interval '2 hour',now()-interval '90 minute')",todayOccurrence,GROUP,series);jdbc.update("INSERT INTO task_occurrence(id,group_id,series_id,revision_no,anchor_date,title,starts_at,ends_at) VALUES (?,?,?,1,current_date+1,'08:00 복약 챙기기',date_trunc('day',now())+interval '1 day 8 hour',date_trunc('day',now())+interval '1 day 8 hour 30 minute')",tomorrowOccurrence,GROUP,series);jdbc.update("INSERT INTO occurrence_medication(group_id,occurrence_id,medication_id) VALUES (?,?,?),(?,?,?)",GROUP,todayOccurrence,medication,GROUP,tomorrowOccurrence,medication);return medication;});}
    private JsonNode med(String name,LocalDate first,LocalDate last,String time){return medWithTimes(name,first,last,List.of(time));}
    private JsonNode medWithTimes(String name,LocalDate first,LocalDate last,List<String> times){var root=json.createObjectNode();root.put("schemaVersion",1);root.put("name",name);root.put("doseText","0.5정");root.put("frequencyText","하루 "+times.size()+"회");root.put("startsOn",first.toString());root.put("endsOn",last.toString());root.putNull("instructions");root.putNull("supersedesMedicationId");var plans=root.putArray("schedulePlans");for(String time:times){var plan=plans.addObject();plan.put("recurrence","DAILY");plan.put("firstDate",first.toString());plan.put("lastDate",last.toString());plan.putArray("weekdays");plan.put("localTime",time);plan.put("durationMinutes",30);}return root;}
    private record Fixture(UUID encounter,UUID revision,List<UUID> items){ }
}
