const $=id=>document.getElementById(id);let subscriptionId=null;
const status=value=>$('status').textContent=value;
const api=async(path,options={})=>{const token=$('token').value.trim();if(!token)throw new Error('Bearer token이 필요합니다.');const response=await fetch($('base').value.replace(/\/$/,'')+path,{...options,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(options.headers||{})},cache:'no-store'});if(!response.ok)throw new Error(`${path}: HTTP ${response.status}`);return response.status===204?null:response.json();};
const b64=value=>{const padding='='.repeat((4-value.length%4)%4);return Uint8Array.from(atob((value+padding).replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));};
const encoded=value=>btoa(String.fromCharCode(...new Uint8Array(value))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
$('login').onclick=async()=>{try{const base=$('base').value.replace(/\/$/,'');const loginKey=$('loginKey').value.trim();if(!loginKey)throw new Error('loginKey가 필요합니다.');const response=await fetch(base+'/api/v1/auth/demo-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({loginKey}),cache:'no-store'});if(!response.ok)throw new Error(`A02: HTTP ${response.status}`);$('token').value=(await response.json()).data.accessToken;status('로컬 demo 로그인 완료. 토큰은 이 페이지 메모리에만 유지됩니다.');}catch(e){status(e.message);}};
$('subscribe').onclick=async()=>{try{if(!isSecureContext)throw new Error('localhost 또는 HTTPS 보안 컨텍스트가 필요합니다.');const config=(await api('/api/v1/push/config')).data;if(!config.enabled)throw new Error('서버 Push 설정이 비활성입니다.');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error(`알림 권한: ${permission}`);const registration=await navigator.serviceWorker.register('./sw.js');const sub=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(config.applicationServerKey)});const keys=sub.toJSON().keys;const result=await api('/api/v1/me/push-subscriptions',{method:'POST',body:JSON.stringify({endpoint:sub.endpoint,keys:{p256dh:keys.p256dh,auth:keys.auth}})});subscriptionId=result.data.id;status('현재 기기 구독 등록 완료. provider 수락과 실제 표시 여부는 별도로 기록하세요.');}catch(e){status(e.message);}};
$('inbox').onclick=()=>refreshInbox().catch(e=>status(e.message));
$('unsubscribe').onclick=async()=>{try{if(!subscriptionId){const values=(await api('/api/v1/me/push-subscriptions')).data.items;if(values.length!==1)throw new Error('현재 세션의 subscriptionId를 특정할 수 없습니다. 등록 직후 해제하거나 서버 목록을 확인하세요.');subscriptionId=values[0].id;}await api(`/api/v1/me/push-subscriptions/${subscriptionId}`,{method:'DELETE'});const registration=await navigator.serviceWorker.getRegistration();const sub=await registration?.pushManager.getSubscription();await sub?.unsubscribe();subscriptionId=null;status('현재 기기만 해제했습니다. 다른 기기 목록은 N07로 확인하세요.');}catch(e){status(e.message);}};
$('clear').onclick=async()=>{const registration=await navigator.serviceWorker.getRegistration();const sub=await registration?.pushManager.getSubscription();await sub?.unsubscribe();subscriptionId=null;$('token').value='';status('메모리 토큰과 현재 브라우저 구독을 정리했습니다. 계정 전환 전에는 먼저 N08도 호출하세요.');};
async function refreshInbox(eventId){const page=(await api('/api/v1/me/notifications?limit=50')).data;const item=eventId?page.items.find(v=>v.eventId===eventId):null;if(item?.target){const path=item.target.type==='TASK'?`/api/v1/tasks/${item.target.id}`:`/api/v1/encounters/${item.target.id}`;await api(path);status(`알림과 ${item.target.type} 대상을 인증 후 재조회했습니다. readAt=${item.readAt??'null'} (명시적 N02 전에는 null이어야 함)`);}else status(`알림 ${page.items.length}건, unread=${page.unreadCount}. 클릭 대상이 없거나 일반 조회입니다.`);}
navigator.serviceWorker?.addEventListener('message',event=>{if(event.data?.type==='notification-click')refreshInbox(event.data.eventId).catch(e=>status(e.message));});
window.addEventListener('beforeunload',()=>{$('token').value='';});
